### ISSUE TITLE
Translate User Guide (Markdown Files) to Spanish

### ISSUE THREAD

**Issue by galoget** [solus-project/help-center-docs#1]
I want to contribute to this project with translations in Spanish, are you interested?

**Comment by JoshStrobl** [comment]
Absolutely. You're welcome to fork the repository and work on the User Guide in a `content/es` folder and base the work off `content/en` :heart: It is all just Markdown so it shouldn't be too complicated :smile:

**Comment by galoget** [comment]
Ok, sure, I'll work on this the following days, do you have an email address for contact?

**Comment by JoshStrobl** [comment]
> do you have an email address for contact?

I would prefer you ask any questions here for public record and to assist anyone else in the future.

**Comment by galoget** [comment]
Ok, no problem. =)

**Comment by JoshStrobl** [comment]
Closing since this is technically not an issue and the structure has since changed. Each article has its own language.md file, for instance en.md or in this context, es.md.
