### ISSUE TITLE
More Detailed HTTPD/PHP Instructions

### ISSUE THREAD

**Issue by johns2s** [solus-project/help-center-docs#102]
It would be nice if the PHP integration instructions from [this](https://solus-project.com/forums/viewtopic.php?t=7440) tutorial were integrated into the help center's HTTPD page.

**Comment by JoshStrobl** [comment]
@johns2s The changes in that tutorial look more like changes that should be made the package itself to "just work" like nginx does. There is no reason you should have to create that `php.conf` but rather that should be supplied by us, the vendor.

**Comment by JoshStrobl** [comment]
Was resolved with #117
