### ISSUE TITLE
Advice: Make the home page more readable

### ISSUE THREAD

**Issue by tristan957** [solus-project/help-center-docs#11]
First time going on the site, I noticed that the home page is a little lacking in readability. For example, the popular categories are all in one column. I think the webpage could benefit from a 2 column look. Also the subtitles for the categories share the font color as the category titles. I think if the subtitles were changed to black the home page could really benefit.

Just some suggestions.

**Comment by JoshStrobl** [comment]
> I noticed that the home page is a little lacking in readability

I appreciate your opinion, but those category sections passes WCAG 2.0 contrast compliance. As far as testing is concerned, it's perfectly readable, including for vision-impaired individuals.

>  For example, the popular categories are all in one column.

On mobile it'll always be one-column. On desktop it's a 3-column wide view no matter the resolution. So not entirely sure what you mean.

![screenshot from 2017-02-19 21-39-01](https://cloud.githubusercontent.com/assets/156574/23105703/dd0fbf10-f6eb-11e6-9907-a51a1223c96b.png)

> Also the subtitles for the categories share the font color as the category titles. I think if the subtitles were changed to black the home page could really benefit.

I'll change the category links to use the same color as the header (like Popular Categories) so there is some differentiation.

---

Note: This repo is only for documentation, not Help Center design feedback. You're welcome to reach out in IRC if you have further design feedback.

**Comment by tristan957** [comment]
Oh that is not what it looks like to me on Chrome on Solus. That looks really good. I would not have made an issue if I saw that

**Comment by tristan957** [comment]
![help center](https://cloud.githubusercontent.com/assets/11936772/23105731/3a185c64-f6a9-11e6-928a-5a277a2296dd.png)
For reference this is what I am seeing on Chrome 56

**Comment by JoshStrobl** [comment]
Your cache is outdated...
