### ISSUE TITLE
Link shouldn't be there...

### ISSUE THREAD

**Issue by ICA3DaR5** [solus-project/help-center-docs#114]
I noticed that on Hardware > Wireless Chipsets under Intel, the driver **Intel Corporation Wireless 8265 / 8275 8086:24fd** shows partly as a dead link. It shouldn't be a link at all.

![screenshot from 2018-01-05 20-38-38](https://user-images.githubusercontent.com/34237682/34623161-c0c2fec6-f258-11e7-9e49-5df7d804f663.png)

**Comment by JoshStrobl** [comment]
It's because Hugo / blackfriday is parsing `[8086:24fd] (rev 78)` as a link.

**Comment by JoshStrobl** [comment]
I'll get this deployed tomorrow. Thanks for the report :)
