### ISSUE TITLE
Add changing kernels section

### ISSUE THREAD

**Issue by baimafeima** [solus-project/help-center-docs#115]
It would be great to add a section on how to change kernels in the _Configuration_ section: https://solus-project.com/articles/configuration/
An article could cover basics such as: 
1. What is a kernel and why would you change it?
2. What terminal command shows the currently installed kernel?
3. What software from the repositories can be used to display the currently installed kernel?
4. How to change kernels via terminal commands. 
5. How to revert the changes. 

I currently have to ask via IRC because I am not sure about these issues and couldn't find any information regarding these questions in the help center.

**Comment by JoshStrobl** [comment]
There is already https://solus-project.com/articles/troubleshooting/boot-management/en/#installing-an-alternative-kernel for switching kernels.
