### ISSUE TITLE
Missing a period

### ISSUE THREAD

**Issue by tristan957** [solus-project/help-center-docs#15]
Small error I noticed. You are missing a period at the end of the packaging paragraph on this https://solus-project.com/articles/contributing/getting-involved/en/

**Comment by tristan957** [comment]
I'm the future how would you like these tiny things handled? Just open a new issue?

**Comment by JoshStrobl** [comment]
Could probably just ping me on IRC or gather up a list of fixes and throw them in a task :+1:

**Comment by tristan957** [comment]
Will do

**Comment by ikeydoherty** [comment]
This made me think of https://www.youtube.com/watch?v=EShUeudtaFg ... I'm sorry. xD
