### ISSUE TITLE
The search box does not seem to work (yet?)

### ISSUE THREAD

**Issue by kyrios123** [solus-project/help-center-docs#19]
When I type something in the search box and I press enter, nothing happen

**Comment by JoshStrobl** [comment]
Resolved. I have an endpoint fix that'll be deployed today.

In the future, don't file Help Center issues here. This is for the docs. Just ping me on IRC.

**Comment by kyrios123** [comment]
okay, no problem.
good you tell me !

**Comment by JoshStrobl** [comment]
> good you tell me !

Search endpoint fix was deployed, should help with search not returning results :)
