### ISSUE TITLE
Add verification section to Installation

### ISSUE THREAD

**Issue by baimafeima** [solus-project/help-center-docs#22]
Could you add a verification section to _Installation_? I think a precise step by step guide on how to verify downloaded .iso and .sha256sum files would be very helpful. I realized that most information on verification found elsewhere is either leaving out important steps, assuming too much knowledge about the subject and ultimately leaving a less-informed user more vulnerable than an experienced one.

**Comment by ikeydoherty** [comment]
How would you go about this on Windows, out of interest..?

**Comment by yursan9** [comment]
From Microsoft's mouth... 
`PS C:\> Get-FileHash $pshome\powershell.exe | Format-List`

https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.utility/get-filehash

**Comment by baimafeima** [comment]
In addition to what @yursan9 has mentioned, _programs_ on Windows can be verified like this (see screenshots/Hexchat example): https://hexchat.github.io/news/hexchat-and-antivirus.html
As Windows comes mostly pre-installed as OEM software, most typical Windows users have probably never dealt with verification issues of the operating system itself.

**Comment by baimafeima** [comment]
A quick follow-up on how other operating systems deal with this. 

(1) The openSUSE verification section is too rudimentary, assuming too much knowledge: https://en.opensuse.org/openSUSE:Tumbleweed_installation
`To verify the signature, download the .sha256 file and run gpg --verify on it. The file must be signed by opensuse@opensuse.org with fingerprint 22C0 7BA5 3417 8CD0 2EFE 22AA B88B 2FD4 3DBD C284. Then run sha256sum --check on the sha256 file to make sure the iso is intact. `
A beginner surely does not know how to run gpg --verify "on it", and I have tested this with random people. They have no idea. A proper verification section ideally assumes _zero_ knowledge on part of the user: 

(2) Ubuntu MATE is doing better in explaining the actual steps but divides into a _quick_ and _secure_ method which is not reasonable in my view: https://ubuntu-mate.org/how-to-verify-downloads/ 
They also still offer downloads via http instead of https because the image is hosted on the ubuntu.com site: https://ubuntu-mate.org/download/

**Comment by baimafeima** [comment]
Some more thoughts about this: In addition to describing each step for each platform (Solus, macOS, Windows10, etc.), a longer term goal could be to develop a cross-platform verification tool with a graphical user interface. This would ensure that security is taken seriously without scaring off new users with lengthy and complicated descriptions. 

KaOS has stated in one of their recent blog posts that their IsoWriter (forked from rosa-imagewriter) has "the ability to verify the integrity of the written USB flash drive in comparison to the downloaded ISO file." Users can verify by clicking a verify button. It has its limitations and is not a complete verification but a step in the right direction I believe. More info here:
https://kaosx.us/img/2017/isow.png
https://kaosx.us/news/2017/kaos01/
https://github.com/KaOSx/isowriter

Another informative article about verification: http://www.zdnet.com/article/verifying-the-integrity-of-linux-iso-images/

**Comment by nadershamma** [comment]
I'll have go at writing up some docs on verifying ISO's, I know when I first entered the world of linux as a new user the concept was a little bewildering. I'll see if I can get a draft done within the next couple of weeks, hopefully sooner.

**Comment by baimafeima** [comment]
@nadershamma If you get around to writing an introduction to verification, I've found that Linux Mint has a fairly good summary: https://linuxmint.com/verify.php
A few steps could be made clearer though, especially on providing reasons why verification works that way. But it is already quite good.
