### ISSUE TITLE
Dvorak Layout Crashes the System

### ISSUE THREAD

**Issue by thecreamedcorn** [solus-project/help-center-docs#3]
I'm not really sure if this is the right place to report bugs, but I had an issue in solus when I tried changing the keyboard layout. As soon as I deleted the English (US) layout only leaving the English (dvorak) layout the entire computer screen started flickering before it finally crashed and sent me back to the login screen. Now when I try to reboot and login it will just kick me back to the login screen after a few seconds of displaying the desktop - not to mention that the layout is still qwerty when I type in my password. Basically, it has made the entire system unusable.

**Comment by RDR8** [comment]
Maybe a Budgie issue. [Reference](https://github.com/budgie-desktop/budgie-desktop/issues/740)

**Comment by ikeydoherty** [comment]
Ya it's a duplicate, thanks @RDR8 

@thecreamedcorn this repo is for Solus documentation :) The issue that @RDR8 linked is being tracked for 10.3
