### ISSUE TITLE
add workspaces to configuration docs?

### ISSUE THREAD

**Issue by mcritchlow** [solus-project/help-center-docs#42]
Wondering what you all think of adding a page to the Configuration section for workspaces. Since it's not enabled by default, I think some people might find this helpful to get workspaces enabled in Budgie.

I was thinking essentially a couple screenshots and related text demonstrating:

1. how to add the workspace applet in Raven
2. finding default Keyboard shortcuts for workspaces

I'd be happy to take a pass at this if you think this would be valuable.

**Comment by JoshStrobl** [comment]
I certainly would find documentation on this to be valuable but I do want to clarify that I think this should go in the Budgie section, since the instructions won't apply to either GNOME Shell (which has its own workspace system) or MATE.

**Comment by mcritchlow** [comment]
Cool, I'll take a pass at something and put it up for your review. Excellent point on it being in the Budgie section. Thanks!
