### ISSUE TITLE
Improve desktop agnostic documentation

### ISSUE THREAD

**Issue by JoshStrobl** [solus-project/help-center-docs#44]
Currently, most of the articles in Configuration section assume the use of either the Budgie or GNOME Shell editions. For instance:

- Articles that provides steps for using GNOME Control Center end up omitting MATE.
- Enabling desktop icons assumes the use of the Budgie edition

Ideally, I'd like the articles to be tweaked to:

- Have sections that provide instructions based on the desktop environment you use. **Currently**, Budgie and GNOME are mostly the same, however I'd like to have dedicated sections on MATE and eventually Plasma, once it's fleshed out by @sunnyflunk. Furthermore, with the eventuality that Budgie has its own Control Center, it'd make sense to at least "prepare" for dedicated Budgie sections as well.
  - A good example of Budgie-specific bits would be the Configuring Sound and Sound Devices section, which has information on using Raven.
  - Configuring Keyboard Layout doesn't make any note of the keyboard layout widget in Budgie nor any IBUS info.
  - I'm not sure exactly **how** sections should be divided up, potential ideas (any thoughts @ikeydoherty):
    - `configuration/budgie/changing-backgrounds/en`
    - `configuration/changing-backgrounds/budgie/en`
    - Dedicated sections such as `Budgie`, `GNOME Shell`, `KDE / Plasma`, `MATE` in `configuration/changing-backgrounds/en`

## Checklist of articles that need updated

- [x] Common Tasks: Watching Videos
  - Needs to be updated to reflect that Budgie and GNOME editions come with GNOME MPV, whereas MATE edition comes with VLC.
- [x] Configuration: Changing Backgrounds
- [x] Configuration: Configuring Date and Time
- [x] Configuration: Configuring Default Applications
- [x] Configuration: Configuring Displays
- [x] Configuration: Configuring Keyboard Layout
- [x] Configuration: Configuring Language
- [x] Configuration: Configuring Mouse and Touchpad
- [x] Configuration: Configuring Network
- [x] Configuration: Configuring Sound and Sound Devices
- [x] Configuration: Enabling Desktop Icons
- [x] Configuration: Enabling Workspaces
- [x] Configuration: Managing Users
- [x] Software: GNOME Shell
  - Needs to be changed to **Desktop Environments** with instructions on installing:
    - Budgie with the GNOME Shell or MATE editions
    - GNOME Shell with Budgie or MATE editions
      - Ensure the lightdm / gdm instructions remain intact
    - MATE with Budgie or GNOME Shell editions

**Comment by yursan9** [comment]
I think it's will be better if we have dedicate section for each DE.
I pick the third option.

**Comment by Justinzobel** [comment]
Third option, one page, and info on each DE for configuring x item.

**Comment by JoshStrobl** [comment]
Updated with checklist.

**Comment by JoshStrobl** [comment]
Resolved thanks to all the fantastic work from @mcritchlow and @NeilWB :heart:
