### ISSUE TITLE
Add Printer Compatibility section to Hardware

### ISSUE THREAD

**Issue by baimafeima** [solus-project/help-center-docs#49]
Do you think a new _Printer Compatibility_ section would be beneficial to be added to _Hardware_? I would probably look through such a list of known devices to work OOTB before making a new purchase.

**Comment by JoshStrobl** [comment]
Assuming people actually add their printers to the doc, sure :smile: Having some instructions their for HP printers indicating the end user should install `hplip`wouldn't hurt either.

**Comment by Bridouz** [comment]
Hi,

I will have some spare time next week and plan to work on a *Printer* section for the doc.

As of today the structure I thought is : 

- Introducing cups
- Cups admin on web browser
- system-config-printer
- How to
  - HP
  - Epson

Do you see any other things to add ?

**Comment by JoshStrobl** [comment]
Not really sure most of that is needed, is it? (_I don't own a printer_). Idea is should just be able to install the likes of hplip, make sure it is listed as a printer in the Printers section of GNOME Control Center, then print. Not sure why you would need to fuss about with cups and cups administration.

It's worth noting as well that this page is largely going to be focused on **listing** compatible printers, so ensuring we don't have overly verbose instructions that may not be necessary is important, and limiting the instructions for specific printers, like HP, to their own section and have them listed above the respective compatible printers of the brand (for instance, Epson, Lexmark, HP).

**Comment by Bridouz** [comment]
Sounds good to me, will make a PR tomorrow

**Comment by JoshStrobl** [comment]
@Bridouz How's that PR coming along? :smile:

**Comment by Bridouz** [comment]
PR #91 sent :)
