### ISSUE TITLE
Thunderbird integrating notifications natively

### ISSUE THREAD

**Issue by orschiro** [solus-project/help-center-docs#64]
Shall we cover this by documenting how to install the necessary add-on and have native TB notifications on Solus?

**Comment by JoshStrobl** [comment]
In my opinion, no. It isn't our responsibility to document every possible modification one can make to a piece of software, we're not aiming to be the Arch Wiki here :smile:

**Comment by orschiro** [comment]
Accepted. 

@ikeydoherty what is your opinion if Solus ships Thunderbird with [this add-on](https://addons.mozilla.org/en-US/thunderbird/addon/gnotifier/) preinstalled to enable native notifications for a better user experience?

**Comment by orschiro** [comment]
Never mind, native notifications can be enabled without installing the add-on.

Hidden preference:

> mail.biff.use_system_alert (defaults to false, toggle to true in [≡] > Preferences > Advanced > General > Config Editor).
