### ISSUE TITLE
Instructions for debugging?

### ISSUE THREAD

**Issue by orschiro** [solus-project/help-center-docs#68]
Shall we maybe add instructions for people to debug their system and understand what they are actually using? Sharing some useful commands such as:

```
$ budgie-desktop --version
$ cat /etc/os-release
```

**Comment by JoshStrobl** [comment]
I don't see how either of those commands help with debugging. We know what the latest Budgie version is going to be, because we always ship with the latest, and os-release isn't going to typically matter, seeing as we're a rolling release.

**Comment by ikeydoherty** [comment]
FWIW if we're going to do version specific reporting on Solus it should be `eopkg info $pkgname` based (or indeed `eopkg blame`)

**Comment by orschiro** [comment]
Thank you, appreciated to hear your opinions. It's better to just keep the existing Github issue template when people are reporting bugs.
