### ISSUE TITLE
Show all catagories on help center start page

### ISSUE THREAD

**Issue by Dizeeee** [solus-project/help-center-docs#71]
First time visitors my not realize that there are more categories than what is displayed. I don't know if there is any reasoning behind this choice but I think that having it confuses newer users.

**Comment by orschiro** [comment]
Do you think the "All categories" button can be overlooked easily?

![image](https://user-images.githubusercontent.com/170947/27849275-41bea9d8-614c-11e7-8c6b-1c4d9526452f.png)

**Comment by Dizeeee** [comment]
I honestly skipped over it the first time I was on the help center. I found it fairly quickly but I don't see why it's needed in the first place. To me it's just needless complication.

**Comment by JoshStrobl** [comment]
It's necessarily because I don't *want* every category being listed and the intent is to add more in the future.
