### ISSUE TITLE
Third Party auto-update

### ISSUE THREAD

**Issue by orschiro** [solus-project/help-center-docs#78]
https://solus-project.com/articles/software/third-party/en/:

> If these instructions fail to work please file an issue. To upgrade once installed simply run the commands again. If there is a new version it will be installed.

Can we improve this paragraph? Does it mean that third party updates are installed automatically, too, or does the user have to check for third party updates manually?

**Comment by JoshStrobl** [comment]
What's there to improve. It states "to upgrade once installed simply run the commands again", that's essentially what the Update button on the Third Party section of the Software Center does, there are no automatic updates.

**Comment by orschiro** [comment]
OK, agree. :-)
