### ISSUE TITLE
Add Budgie shortcuts

### ISSUE THREAD

**Issue by baimafeima** [solus-project/help-center-docs#79]
Could you add CTRL + P, Super + L, and ALT + F4 to the list of Budgie shortcuts? 
https://solus-project.com/articles/budgie/shortcuts/en/
I think it would also be helpful to briefly mention that the Superkey is equivalent to the Windows key on many laptops.

**Comment by Bridouz** [comment]
I can do that but I can't find to understand what `Super + P` does exactly ^^

**Comment by baimafeima** [comment]
Ah, should have been CTRL + P.

**Comment by Bridouz** [comment]
CTRL + P does nothing for me, only on Firefox it opens the print screen.

**Comment by baimafeima** [comment]
> CTRL + P does nothing for me, only on Firefox it opens the print screen.

It should work with any application capable of printing (e.g. Firefox, Gedit, LibreOffice Writer, etc.)

**Comment by JoshStrobl** [comment]
That isn't a Budgie shortcut and it's pretty standard for printing. I don't see a reason why that needs to be documented. I'm going to close this issue now that @Bridouz has sorted the others out.
