### ISSUE TITLE
Add new security category in the Help Center

### ISSUE THREAD

**Issue by baimafeima** [solus-project/help-center-docs#96]
I would suggest to bundle a lot of security-related issues under a new security category or tag in the Help Center. The following guides could be part of it:
- How to verify downloaded .iso files?
- How to install CA certificates and import them into openconnect?
Open up the file manager _Files_ and click _+Other Locations_. Select _Computer_. CA certificates are then located under the following path: `/etc/ssl/certs`
- How to import openVPN configuration files?
- How to prevent DNS leaks in openVPN?
- How to protect yourself against browser fingerprinting?
- How to set up iptables?
- How to encrypt your emails?
- How to choose a reliable server for creating an XMPP account?
- A non-technical short common sense guide to safe computing

**Comment by JoshStrobl** [comment]
I don't see why most of these items need to be Help Center documentation, rather than in places like OpenVPN. They aren't Solus-specific really. As for the first item (verify download of ISO files), that can be added, but you've already opened #22 for that.

**Comment by JoshStrobl** [comment]
> It is spread all over the place and users would have to collect this kind of information on different sites.

Yes and our Help Center would be yet another place. Ever seen the XKCD comic on standards? This situation is basically that :smile: 

> The information presented is not consistent. Most documentation is overly technical and not easily understandable for average users.

Then their documentation should be improved, not duplicated or redone elsewhere.
