### ISSUE TITLE
Blu Rays Vlc

### ISSUE THREAD

**Issue by BearzRobotics** [solus-project/help-center-docs#99]
I just got a blu ray drive and had problems setting it up. After doing some googling I found out that i needed to install libaacs and libbdplus. Once installed from the software center, I still couldn't play my blu rays in vlc. I had to go **[here](http://vlc-bluray.whoknowsmy.name/)** and download a key file and put it under ~/.config/aacs and then everything worked fine. So i thought this should be add to watching videos under the help center, because this was the first place I came to try and set everything up.

**Comment by JoshStrobl** [comment]
Closing as wontfix. Those keys were legally questionable (I say were since the website fails to load) and I'd rather not point users to such material.
